import { useAtomValue } from "jotai";
import { type NextPage } from "next";
import Head from "next/head";
import { splitBillAtom } from "~/atoms/home";
import Layout from "~/components/Layout";
import { BillForm } from "~/components/form/BillForm";
import TaxAndAdditionForm from "~/components/form/TaxAndAdditionForm";
import { type People } from "~/types/people";

export type CreateBillForm = {
  peoples: People[];
};
const Home: NextPage = () => {
  const splitBill = useAtomValue(splitBillAtom);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Splitbill baru">
        <div>
          {splitBill.step === 1 && <BillForm />}
          {splitBill.step === 2 && <TaxAndAdditionForm />}
        </div>
      </Layout>
    </>
  );
};

export default Home;
